game_shop2/game_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task1.urls', namespace='task1')),
]

game_shop2/task1/urls.py
from django.urls import path
from . import views

app_name = 'task1'

urlpatterns = [
    path('', views.index, name='index'),
    path('games/', views.game_list, name='game_list'),
    path('cart/', views.cart, name='cart'),
    path('register/', views.register, name='register'),
    path('registration_success/', views.registration_success, name='registration_success'),
]

game_shop2/task1/models.py
from django.db import models

class Buyer(models.Model):
    name = models.CharField(max_length=100, unique=True)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    age = models.IntegerField()

    def __str__(self):
        return self.name

class Game(models.Model):
    title = models.CharField(max_length=200)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    size = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    age_limited = models.BooleanField(default=False)
    buyer = models.ManyToManyField('Buyer', related_name='games')

    def __str__(self):
        return self.title

game_shop2/task1/forms.py
from django import forms

class UserRegister(forms.Form):
    username = forms.CharField(max_length=30, label="Введите логин")
    password = forms.CharField(min_length=8, widget=forms.PasswordInput, label="Введите пароль")
    repeat_password = forms.CharField(min_length=8, widget=forms.PasswordInput, label="Повторите пароль")
    age = forms.IntegerField(min_value=0, max_value=999, label="Введите свой возраст")

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        repeat_password = cleaned_data.get("repeat_password")

        if password != repeat_password:
            raise forms.ValidationError("Пароли не совпадают")
        return cleaned_data

game_shop2/task1/views.py
from django.shortcuts import render, redirect
from .forms import UserRegister
from .models import Buyer, Game


def index(request):
    context = {'title': 'Главная страница'}
    return render(request, 'index.html', context)

def game_list(request):
    games = Game.objects.all()
    context = {'games': games}
    return render(request, 'game_list.html', context)

def cart(request):
    games = []
    context = {'games': games}
    return render(request, 'cart.html', context)

def register(request):
    if request.method == 'POST':
        form = UserRegister(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            name = cleaned_data['username']
            age = cleaned_data['age']


            try:
                Buyer.objects.get(name=name)
                return render(request, 'registration_form.html', {'form':form, 'error_message': 'Покупатель с таким именем уже существует'})
            except Buyer.DoesNotExist:
                Buyer.objects.create(name=name, balance=0, age=age)
                return redirect('registration_success')
        else:
            return render(request, 'registration_form.html', {'form': form})
    else:
        form = UserRegister()
        return render(request, 'registration_form.html', {'form': form})


def registration_success(request):
    return render(request, 'registration_success.html')

game_shop2/templates/cart.html
{% extends 'menu.html' %}

{% block pagename %}Корзина{% endblock %}

{% block content %}
    <h1>Извините, ваша корзина пуста.</h1>
    <ul>
        {% for game in games %}
            <li>{{ game }}</li>
        {% endfor %}
    </ul>
{% endblock %}

game_shop2/templates/game_list.html
{% extends 'menu.html' %}

{% block pagename %}Магазин{% endblock %}

{% block content %}
    <h1>Список игр</h1>
    <ul>
        {% for game in games %}
            <li>{{ game.title }} | {{ game.description }}. Стоимость: {{ game.cost }}
                <button type="button" class="btn btn-primary">Купить</button> </li>
        {% endfor %}
    </ul>
{% endblock %}

game_shop2/templates/index.html
{% extends 'menu.html' %}
{% block pagename %}Главная страница{% endblock %}


game_shop2/templates/menu.html
<!DOCTYPE html>
<html>
<body>
    <div class="container">
        <h1>{% block pagename %}{% endblock %}</h1>
        <nav>
            {% block menu %}
                <ul>
                    <li><a href="{% url 'task1:index' %}">Главная</a></li>
                    <li><a href="{% url 'task1:game_list' %}">Магазин</a></li>
                    <li><a href="{% url 'task1:cart' %}">Корзина</a></li>
                </ul>
            {% endblock %}
        </nav>
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

game_shop2/templates/registration_form.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегистрироваться</button>
</form>

game_shop2/templates/registration_success.html
<h1>Регистрация прошла успешно!</h1>
<p>Вы успешно зарегистрировались.</p>
<a href="/">Вернуться на главную страницу</a>